### ISSUE TITLE
support to xml attributes

### ISSUE THREAD

**Issue by denisdemais** [xphh/easyxml#1]
Hi,
easyxml works perfectlly! but no have support to xml attributes, like:
"
<car id=1 hp=1200>Porshe</car>
"

not is possible retrieve 'id' or 'hp'

kind regards,
Denis

**Comment by xphh** [comment]
esayxml is for "Converting from Lua table to XML" or "Converting from XML to Lua table". 

There is no room for xml attributes in Lua table...

**Comment by denisdemais** [comment]
Hi, works like that.

a suggestion can be, preserv the attribute using a '-' prefix

<xml ...>
<names>
<name age=1>X</name>
<...>
</names>

{
 'names' = { value='X', '-age'=1 }
}

**Comment by denisdemais** [comment]
And works like you say.

Anyway a suggestion are: preserve the xml/attribute to using a '-' prefix.

Just a suggestion.

You lib works very fast to a lua pure parser.

congratulations!

kind regards,
